### PR TITLE
Raise version of minishlink/web-push to ^5.0

### PR DESCRIPTION
**Pull request by juliusstoerrle**
Alternative to #15

### CODE REVIEW

**Comment by Minishlink** [comment]
When you do a fresh install with this, does composer pick web-push v5?

**Comment by Minishlink** [comment]
Have you tested it?

**Comment by juliusstoerrle** [comment]
I have tested it with my prototype which at the moment only injects the service and sends a test message to two endpoints. I also ran the bundles unit test.

Is it correct that you need to iterate over the returned generator to actually send the message? (As soon as I do that, it works as before)

**Comment by Minishlink** [comment]
Yes, see https://github.com/web-push-libs/web-push-php/releases/tag/v5.0.0 :)

**Review by Minishlink — APPROVED** [review]
Thanks!

**Comment by juliusstoerrle** [comment]
I saw those but it wasn't immediatly clear that I MUST iterate over the generator. It makes sense, but I first thought it is only required to get the results.

**Comment by Minishlink** [comment]
Ok, thanks, I edited the changelog.

**Pull request merged**
