### PR TITLE
Make bundle compatible with Symfony 5

### LINKED ISSUE #13: Support Symfony 5
I would like to use this library with Symfony 5.

I have not used the bundle with version 4, therefore I don't know if any deprecations came up. I guess it is only required to update the composer.json?

### PR DESCRIPTION
**Pull request by juliusstoerrle**
Update composer.json to include Symfony V5.

Fixes #13 

I have NOT tested the changes yet.

### CODE REVIEW

**Comment by Minishlink** [comment]
Let me know when you have tested it, and I'll merge, thanks!

**Comment by juliusstoerrle** [comment]
As the TreeBuilder changed I had to update the code aswell. The constructor parameter of the TreeBuilder is only available since 4.2. I therefore also raised the minimum required symfony version to 4.2.

I think it is alright, but people still using symfony 3.4 will need to use a previous version of this library.

**Comment by juliusstoerrle** [comment]
I tested this branch with Symfony version 5 and it worked without problems so far. From my side it would be ready for a merge.

**Review by Minishlink — APPROVED** [review]
Thanks! 👍

**Pull request merged**
