### PR TITLE
Fix BC break with WebPush library 1.4

### PR DESCRIPTION
**Pull request by gab3sz**

### CODE REVIEW

**Comment by Minishlink** [comment]
Thanks @gab3sz!

**Comment by tgabi333** [comment]
@Minishlink could you please make a new release, since now it is broken. Thanks :)

**Comment by Minishlink** [comment]
@tgabi333 Done :) I'll add a new config parameter for the client options when I can.

**Comment by tgabi333** [comment]
Thank you very much :)

**Pull request merged**
